/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IAgenticID,
  IAgenticIDInterface,
} from "../../AgentRegistry.sol/IAgenticID";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "exists",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "ownerOf",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IAgenticID__factory {
  static readonly abi = _abi;
  static createInterface(): IAgenticIDInterface {
    return new Interface(_abi) as IAgenticIDInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IAgenticID {
    return new Contract(address, _abi, runner) as unknown as IAgenticID;
  }
}
