/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface FeeRouterInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "admin"
      | "creatorFeeBps"
      | "pendingWithdrawals"
      | "platformTreasury"
      | "registry"
      | "route"
      | "setCreatorFeeBps"
      | "setPlatformTreasury"
      | "setSubscriptionManager"
      | "subscriptionManager"
      | "transferAdmin"
      | "withdraw"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CreatorFeeBpsUpdated"
      | "FeesRouted"
      | "TreasuryUpdated"
      | "Withdrawal"
  ): EventFragment;

  encodeFunctionData(functionFragment: "admin", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "creatorFeeBps",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "pendingWithdrawals",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "platformTreasury",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "registry", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "route",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setCreatorFeeBps",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setPlatformTreasury",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setSubscriptionManager",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "subscriptionManager",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferAdmin",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "withdraw", values?: undefined): string;

  decodeFunctionResult(functionFragment: "admin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "creatorFeeBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pendingWithdrawals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "platformTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "registry", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "route", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setCreatorFeeBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPlatformTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSubscriptionManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "subscriptionManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
}

export namespace CreatorFeeBpsUpdatedEvent {
  export type InputTuple = [tier: BigNumberish, newBps: BigNumberish];
  export type OutputTuple = [tier: bigint, newBps: bigint];
  export interface OutputObject {
    tier: bigint;
    newBps: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FeesRoutedEvent {
  export type InputTuple = [
    nodeId: AddressLike,
    creator: AddressLike,
    creatorAmount: BigNumberish,
    platformAmount: BigNumberish,
    tier: BigNumberish
  ];
  export type OutputTuple = [
    nodeId: string,
    creator: string,
    creatorAmount: bigint,
    platformAmount: bigint,
    tier: bigint
  ];
  export interface OutputObject {
    nodeId: string;
    creator: string;
    creatorAmount: bigint;
    platformAmount: bigint;
    tier: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TreasuryUpdatedEvent {
  export type InputTuple = [newTreasury: AddressLike];
  export type OutputTuple = [newTreasury: string];
  export interface OutputObject {
    newTreasury: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawalEvent {
  export type InputTuple = [creator: AddressLike, amount: BigNumberish];
  export type OutputTuple = [creator: string, amount: bigint];
  export interface OutputObject {
    creator: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface FeeRouter extends BaseContract {
  connect(runner?: ContractRunner | null): FeeRouter;
  waitForDeployment(): Promise<this>;

  interface: FeeRouterInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  admin: TypedContractMethod<[], [string], "view">;

  creatorFeeBps: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  pendingWithdrawals: TypedContractMethod<
    [arg0: AddressLike],
    [bigint],
    "view"
  >;

  platformTreasury: TypedContractMethod<[], [string], "view">;

  registry: TypedContractMethod<[], [string], "view">;

  route: TypedContractMethod<
    [nodeId: AddressLike, tier: BigNumberish],
    [void],
    "payable"
  >;

  setCreatorFeeBps: TypedContractMethod<
    [tier: BigNumberish, bps: BigNumberish],
    [void],
    "nonpayable"
  >;

  setPlatformTreasury: TypedContractMethod<
    [newTreasury: AddressLike],
    [void],
    "nonpayable"
  >;

  setSubscriptionManager: TypedContractMethod<
    [_sm: AddressLike],
    [void],
    "nonpayable"
  >;

  subscriptionManager: TypedContractMethod<[], [string], "view">;

  transferAdmin: TypedContractMethod<
    [newAdmin: AddressLike],
    [void],
    "nonpayable"
  >;

  withdraw: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "admin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "creatorFeeBps"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "pendingWithdrawals"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "platformTreasury"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "route"
  ): TypedContractMethod<
    [nodeId: AddressLike, tier: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "setCreatorFeeBps"
  ): TypedContractMethod<
    [tier: BigNumberish, bps: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setPlatformTreasury"
  ): TypedContractMethod<[newTreasury: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setSubscriptionManager"
  ): TypedContractMethod<[_sm: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "subscriptionManager"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "transferAdmin"
  ): TypedContractMethod<[newAdmin: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "CreatorFeeBpsUpdated"
  ): TypedContractEvent<
    CreatorFeeBpsUpdatedEvent.InputTuple,
    CreatorFeeBpsUpdatedEvent.OutputTuple,
    CreatorFeeBpsUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "FeesRouted"
  ): TypedContractEvent<
    FeesRoutedEvent.InputTuple,
    FeesRoutedEvent.OutputTuple,
    FeesRoutedEvent.OutputObject
  >;
  getEvent(
    key: "TreasuryUpdated"
  ): TypedContractEvent<
    TreasuryUpdatedEvent.InputTuple,
    TreasuryUpdatedEvent.OutputTuple,
    TreasuryUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Withdrawal"
  ): TypedContractEvent<
    WithdrawalEvent.InputTuple,
    WithdrawalEvent.OutputTuple,
    WithdrawalEvent.OutputObject
  >;

  filters: {
    "CreatorFeeBpsUpdated(uint8,uint16)": TypedContractEvent<
      CreatorFeeBpsUpdatedEvent.InputTuple,
      CreatorFeeBpsUpdatedEvent.OutputTuple,
      CreatorFeeBpsUpdatedEvent.OutputObject
    >;
    CreatorFeeBpsUpdated: TypedContractEvent<
      CreatorFeeBpsUpdatedEvent.InputTuple,
      CreatorFeeBpsUpdatedEvent.OutputTuple,
      CreatorFeeBpsUpdatedEvent.OutputObject
    >;

    "FeesRouted(address,address,uint256,uint256,uint8)": TypedContractEvent<
      FeesRoutedEvent.InputTuple,
      FeesRoutedEvent.OutputTuple,
      FeesRoutedEvent.OutputObject
    >;
    FeesRouted: TypedContractEvent<
      FeesRoutedEvent.InputTuple,
      FeesRoutedEvent.OutputTuple,
      FeesRoutedEvent.OutputObject
    >;

    "TreasuryUpdated(address)": TypedContractEvent<
      TreasuryUpdatedEvent.InputTuple,
      TreasuryUpdatedEvent.OutputTuple,
      TreasuryUpdatedEvent.OutputObject
    >;
    TreasuryUpdated: TypedContractEvent<
      TreasuryUpdatedEvent.InputTuple,
      TreasuryUpdatedEvent.OutputTuple,
      TreasuryUpdatedEvent.OutputObject
    >;

    "Withdrawal(address,uint256)": TypedContractEvent<
      WithdrawalEvent.InputTuple,
      WithdrawalEvent.OutputTuple,
      WithdrawalEvent.OutputObject
    >;
    Withdrawal: TypedContractEvent<
      WithdrawalEvent.InputTuple,
      WithdrawalEvent.OutputTuple,
      WithdrawalEvent.OutputObject
    >;
  };
}
