/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  DeployContractOptions,
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "AgentRegistry",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AgentRegistry__factory>;
    getContractFactory(
      name: "IAgenticID",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IAgenticID__factory>;
    getContractFactory(
      name: "FeeRouter",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.FeeRouter__factory>;
    getContractFactory(
      name: "PointVault",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PointVault__factory>;
    getContractFactory(
      name: "ReputationOracle",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ReputationOracle__factory>;
    getContractFactory(
      name: "SubscriptionManager",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SubscriptionManager__factory>;

    getContractAt(
      name: "AgentRegistry",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.AgentRegistry>;
    getContractAt(
      name: "IAgenticID",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IAgenticID>;
    getContractAt(
      name: "FeeRouter",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.FeeRouter>;
    getContractAt(
      name: "PointVault",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.PointVault>;
    getContractAt(
      name: "ReputationOracle",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ReputationOracle>;
    getContractAt(
      name: "SubscriptionManager",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.SubscriptionManager>;

    deployContract(
      name: "AgentRegistry",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.AgentRegistry>;
    deployContract(
      name: "IAgenticID",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IAgenticID>;
    deployContract(
      name: "FeeRouter",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.FeeRouter>;
    deployContract(
      name: "PointVault",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PointVault>;
    deployContract(
      name: "ReputationOracle",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ReputationOracle>;
    deployContract(
      name: "SubscriptionManager",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SubscriptionManager>;

    deployContract(
      name: "AgentRegistry",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.AgentRegistry>;
    deployContract(
      name: "IAgenticID",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IAgenticID>;
    deployContract(
      name: "FeeRouter",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.FeeRouter>;
    deployContract(
      name: "PointVault",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PointVault>;
    deployContract(
      name: "ReputationOracle",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ReputationOracle>;
    deployContract(
      name: "SubscriptionManager",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SubscriptionManager>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
