/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface NodeRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "deregisterNode"
      | "getNodeCount"
      | "getNodes"
      | "nodeList"
      | "nodes"
      | "publishBatch"
      | "registerNode"
      | "verifier"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BatchPublished"
      | "NodeDeregistered"
      | "NodeRegistered"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "deregisterNode",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getNodeCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getNodes",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "nodeList",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "nodes", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "publishBatch",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerNode",
    values: [string, string, string]
  ): string;
  encodeFunctionData(functionFragment: "verifier", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "deregisterNode",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getNodeCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getNodes", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "nodeList", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "nodes", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "publishBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerNode",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "verifier", data: BytesLike): Result;
}

export namespace BatchPublishedEvent {
  export type InputTuple = [rootHash: BytesLike, timestamp: BigNumberish];
  export type OutputTuple = [rootHash: string, timestamp: bigint];
  export interface OutputObject {
    rootHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NodeDeregisteredEvent {
  export type InputTuple = [nodeId: AddressLike];
  export type OutputTuple = [nodeId: string];
  export interface OutputObject {
    nodeId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NodeRegisteredEvent {
  export type InputTuple = [
    nodeId: AddressLike,
    name: string,
    tokenFocus: string,
    creator: AddressLike
  ];
  export type OutputTuple = [
    nodeId: string,
    name: string,
    tokenFocus: string,
    creator: string
  ];
  export interface OutputObject {
    nodeId: string;
    name: string;
    tokenFocus: string;
    creator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface NodeRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): NodeRegistry;
  waitForDeployment(): Promise<this>;

  interface: NodeRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  deregisterNode: TypedContractMethod<[], [void], "nonpayable">;

  getNodeCount: TypedContractMethod<[], [bigint], "view">;

  getNodes: TypedContractMethod<
    [offset: BigNumberish, limit: BigNumberish],
    [string[]],
    "view"
  >;

  nodeList: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  nodes: TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, string, string, boolean, bigint] & {
        name: string;
        tokenFocus: string;
        description: string;
        creator: string;
        active: boolean;
        registeredAt: bigint;
      }
    ],
    "view"
  >;

  publishBatch: TypedContractMethod<
    [rootHash: BytesLike],
    [void],
    "nonpayable"
  >;

  registerNode: TypedContractMethod<
    [name: string, tokenFocus: string, description: string],
    [void],
    "nonpayable"
  >;

  verifier: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "deregisterNode"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getNodeCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getNodes"
  ): TypedContractMethod<
    [offset: BigNumberish, limit: BigNumberish],
    [string[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "nodeList"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "nodes"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, string, string, boolean, bigint] & {
        name: string;
        tokenFocus: string;
        description: string;
        creator: string;
        active: boolean;
        registeredAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "publishBatch"
  ): TypedContractMethod<[rootHash: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "registerNode"
  ): TypedContractMethod<
    [name: string, tokenFocus: string, description: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "verifier"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "BatchPublished"
  ): TypedContractEvent<
    BatchPublishedEvent.InputTuple,
    BatchPublishedEvent.OutputTuple,
    BatchPublishedEvent.OutputObject
  >;
  getEvent(
    key: "NodeDeregistered"
  ): TypedContractEvent<
    NodeDeregisteredEvent.InputTuple,
    NodeDeregisteredEvent.OutputTuple,
    NodeDeregisteredEvent.OutputObject
  >;
  getEvent(
    key: "NodeRegistered"
  ): TypedContractEvent<
    NodeRegisteredEvent.InputTuple,
    NodeRegisteredEvent.OutputTuple,
    NodeRegisteredEvent.OutputObject
  >;

  filters: {
    "BatchPublished(bytes32,uint256)": TypedContractEvent<
      BatchPublishedEvent.InputTuple,
      BatchPublishedEvent.OutputTuple,
      BatchPublishedEvent.OutputObject
    >;
    BatchPublished: TypedContractEvent<
      BatchPublishedEvent.InputTuple,
      BatchPublishedEvent.OutputTuple,
      BatchPublishedEvent.OutputObject
    >;

    "NodeDeregistered(address)": TypedContractEvent<
      NodeDeregisteredEvent.InputTuple,
      NodeDeregisteredEvent.OutputTuple,
      NodeDeregisteredEvent.OutputObject
    >;
    NodeDeregistered: TypedContractEvent<
      NodeDeregisteredEvent.InputTuple,
      NodeDeregisteredEvent.OutputTuple,
      NodeDeregisteredEvent.OutputObject
    >;

    "NodeRegistered(address,string,string,address)": TypedContractEvent<
      NodeRegisteredEvent.InputTuple,
      NodeRegisteredEvent.OutputTuple,
      NodeRegisteredEvent.OutputObject
    >;
    NodeRegistered: TypedContractEvent<
      NodeRegisteredEvent.InputTuple,
      NodeRegisteredEvent.OutputTuple,
      NodeRegisteredEvent.OutputObject
    >;
  };
}
