/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface ReputationOracleInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "acceptVerifier"
      | "getScore"
      | "getTier"
      | "pendingVerifier"
      | "proposeVerifier"
      | "scores"
      | "updateScore"
      | "verifier"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ScoreUpdated"
      | "TierChanged"
      | "VerifierTransferProposed"
      | "VerifierTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "acceptVerifier",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getScore",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTier",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "pendingVerifier",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "proposeVerifier",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "scores", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "updateScore",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "verifier", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "acceptVerifier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getScore", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getTier", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingVerifier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proposeVerifier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "scores", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "verifier", data: BytesLike): Result;
}

export namespace ScoreUpdatedEvent {
  export type InputTuple = [
    nodeId: AddressLike,
    score: BigNumberish,
    tier: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    nodeId: string,
    score: bigint,
    tier: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    nodeId: string;
    score: bigint;
    tier: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TierChangedEvent {
  export type InputTuple = [
    nodeId: AddressLike,
    oldTier: BigNumberish,
    newTier: BigNumberish
  ];
  export type OutputTuple = [nodeId: string, oldTier: bigint, newTier: bigint];
  export interface OutputObject {
    nodeId: string;
    oldTier: bigint;
    newTier: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VerifierTransferProposedEvent {
  export type InputTuple = [proposed: AddressLike];
  export type OutputTuple = [proposed: string];
  export interface OutputObject {
    proposed: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VerifierTransferredEvent {
  export type InputTuple = [oldVerifier: AddressLike, newVerifier: AddressLike];
  export type OutputTuple = [oldVerifier: string, newVerifier: string];
  export interface OutputObject {
    oldVerifier: string;
    newVerifier: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ReputationOracle extends BaseContract {
  connect(runner?: ContractRunner | null): ReputationOracle;
  waitForDeployment(): Promise<this>;

  interface: ReputationOracleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  acceptVerifier: TypedContractMethod<[], [void], "nonpayable">;

  getScore: TypedContractMethod<
    [nodeId: AddressLike],
    [
      [bigint, bigint, bigint] & {
        score: bigint;
        tier: bigint;
        updatedAt: bigint;
      }
    ],
    "view"
  >;

  getTier: TypedContractMethod<[nodeId: AddressLike], [bigint], "view">;

  pendingVerifier: TypedContractMethod<[], [string], "view">;

  proposeVerifier: TypedContractMethod<
    [proposed: AddressLike],
    [void],
    "nonpayable"
  >;

  scores: TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint] & {
        score: bigint;
        tier: bigint;
        updatedAt: bigint;
      }
    ],
    "view"
  >;

  updateScore: TypedContractMethod<
    [nodeId: AddressLike, score: BigNumberish, tier: BigNumberish],
    [void],
    "nonpayable"
  >;

  verifier: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "acceptVerifier"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getScore"
  ): TypedContractMethod<
    [nodeId: AddressLike],
    [
      [bigint, bigint, bigint] & {
        score: bigint;
        tier: bigint;
        updatedAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTier"
  ): TypedContractMethod<[nodeId: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "pendingVerifier"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "proposeVerifier"
  ): TypedContractMethod<[proposed: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "scores"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint] & {
        score: bigint;
        tier: bigint;
        updatedAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "updateScore"
  ): TypedContractMethod<
    [nodeId: AddressLike, score: BigNumberish, tier: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "verifier"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "ScoreUpdated"
  ): TypedContractEvent<
    ScoreUpdatedEvent.InputTuple,
    ScoreUpdatedEvent.OutputTuple,
    ScoreUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "TierChanged"
  ): TypedContractEvent<
    TierChangedEvent.InputTuple,
    TierChangedEvent.OutputTuple,
    TierChangedEvent.OutputObject
  >;
  getEvent(
    key: "VerifierTransferProposed"
  ): TypedContractEvent<
    VerifierTransferProposedEvent.InputTuple,
    VerifierTransferProposedEvent.OutputTuple,
    VerifierTransferProposedEvent.OutputObject
  >;
  getEvent(
    key: "VerifierTransferred"
  ): TypedContractEvent<
    VerifierTransferredEvent.InputTuple,
    VerifierTransferredEvent.OutputTuple,
    VerifierTransferredEvent.OutputObject
  >;

  filters: {
    "ScoreUpdated(address,uint256,uint8,uint256)": TypedContractEvent<
      ScoreUpdatedEvent.InputTuple,
      ScoreUpdatedEvent.OutputTuple,
      ScoreUpdatedEvent.OutputObject
    >;
    ScoreUpdated: TypedContractEvent<
      ScoreUpdatedEvent.InputTuple,
      ScoreUpdatedEvent.OutputTuple,
      ScoreUpdatedEvent.OutputObject
    >;

    "TierChanged(address,uint8,uint8)": TypedContractEvent<
      TierChangedEvent.InputTuple,
      TierChangedEvent.OutputTuple,
      TierChangedEvent.OutputObject
    >;
    TierChanged: TypedContractEvent<
      TierChangedEvent.InputTuple,
      TierChangedEvent.OutputTuple,
      TierChangedEvent.OutputObject
    >;

    "VerifierTransferProposed(address)": TypedContractEvent<
      VerifierTransferProposedEvent.InputTuple,
      VerifierTransferProposedEvent.OutputTuple,
      VerifierTransferProposedEvent.OutputObject
    >;
    VerifierTransferProposed: TypedContractEvent<
      VerifierTransferProposedEvent.InputTuple,
      VerifierTransferProposedEvent.OutputTuple,
      VerifierTransferProposedEvent.OutputObject
    >;

    "VerifierTransferred(address,address)": TypedContractEvent<
      VerifierTransferredEvent.InputTuple,
      VerifierTransferredEvent.OutputTuple,
      VerifierTransferredEvent.OutputObject
    >;
    VerifierTransferred: TypedContractEvent<
      VerifierTransferredEvent.InputTuple,
      VerifierTransferredEvent.OutputTuple,
      VerifierTransferredEvent.OutputObject
    >;
  };
}
