/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface SubscriptionManagerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "admin"
      | "feeRouter"
      | "isSubscribed"
      | "priceFor"
      | "reputationOracle"
      | "setSubscriptionDuration"
      | "setTierPrice"
      | "subscribe"
      | "subscriptionDuration"
      | "subscriptionEnd"
      | "subscriptions"
      | "tierPrices"
      | "transferAdmin"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DurationUpdated"
      | "Subscribed"
      | "TierPriceUpdated"
  ): EventFragment;

  encodeFunctionData(functionFragment: "admin", values?: undefined): string;
  encodeFunctionData(functionFragment: "feeRouter", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "isSubscribed",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "priceFor",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "reputationOracle",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setSubscriptionDuration",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setTierPrice",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "subscribe",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "subscriptionDuration",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "subscriptionEnd",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "subscriptions",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "tierPrices",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferAdmin",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "admin", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "feeRouter", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isSubscribed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "priceFor", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "reputationOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSubscriptionDuration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTierPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "subscribe", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "subscriptionDuration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "subscriptionEnd",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "subscriptions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "tierPrices", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferAdmin",
    data: BytesLike
  ): Result;
}

export namespace DurationUpdatedEvent {
  export type InputTuple = [newDuration: BigNumberish];
  export type OutputTuple = [newDuration: bigint];
  export interface OutputObject {
    newDuration: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SubscribedEvent {
  export type InputTuple = [
    subscriber: AddressLike,
    nodeId: AddressLike,
    endTime: BigNumberish,
    amountPaid: BigNumberish
  ];
  export type OutputTuple = [
    subscriber: string,
    nodeId: string,
    endTime: bigint,
    amountPaid: bigint
  ];
  export interface OutputObject {
    subscriber: string;
    nodeId: string;
    endTime: bigint;
    amountPaid: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TierPriceUpdatedEvent {
  export type InputTuple = [tier: BigNumberish, newPrice: BigNumberish];
  export type OutputTuple = [tier: bigint, newPrice: bigint];
  export interface OutputObject {
    tier: bigint;
    newPrice: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SubscriptionManager extends BaseContract {
  connect(runner?: ContractRunner | null): SubscriptionManager;
  waitForDeployment(): Promise<this>;

  interface: SubscriptionManagerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  admin: TypedContractMethod<[], [string], "view">;

  feeRouter: TypedContractMethod<[], [string], "view">;

  isSubscribed: TypedContractMethod<
    [user: AddressLike, nodeId: AddressLike],
    [boolean],
    "view"
  >;

  priceFor: TypedContractMethod<[nodeId: AddressLike], [bigint], "view">;

  reputationOracle: TypedContractMethod<[], [string], "view">;

  setSubscriptionDuration: TypedContractMethod<
    [durationSeconds: BigNumberish],
    [void],
    "nonpayable"
  >;

  setTierPrice: TypedContractMethod<
    [tier: BigNumberish, price: BigNumberish],
    [void],
    "nonpayable"
  >;

  subscribe: TypedContractMethod<[nodeId: AddressLike], [void], "payable">;

  subscriptionDuration: TypedContractMethod<[], [bigint], "view">;

  subscriptionEnd: TypedContractMethod<
    [user: AddressLike, nodeId: AddressLike],
    [bigint],
    "view"
  >;

  subscriptions: TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [
      [bigint, bigint, bigint] & {
        startTime: bigint;
        endTime: bigint;
        amountPaid: bigint;
      }
    ],
    "view"
  >;

  tierPrices: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  transferAdmin: TypedContractMethod<
    [newAdmin: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "admin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "feeRouter"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "isSubscribed"
  ): TypedContractMethod<
    [user: AddressLike, nodeId: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "priceFor"
  ): TypedContractMethod<[nodeId: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "reputationOracle"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setSubscriptionDuration"
  ): TypedContractMethod<[durationSeconds: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setTierPrice"
  ): TypedContractMethod<
    [tier: BigNumberish, price: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "subscribe"
  ): TypedContractMethod<[nodeId: AddressLike], [void], "payable">;
  getFunction(
    nameOrSignature: "subscriptionDuration"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "subscriptionEnd"
  ): TypedContractMethod<
    [user: AddressLike, nodeId: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "subscriptions"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [
      [bigint, bigint, bigint] & {
        startTime: bigint;
        endTime: bigint;
        amountPaid: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "tierPrices"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferAdmin"
  ): TypedContractMethod<[newAdmin: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "DurationUpdated"
  ): TypedContractEvent<
    DurationUpdatedEvent.InputTuple,
    DurationUpdatedEvent.OutputTuple,
    DurationUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Subscribed"
  ): TypedContractEvent<
    SubscribedEvent.InputTuple,
    SubscribedEvent.OutputTuple,
    SubscribedEvent.OutputObject
  >;
  getEvent(
    key: "TierPriceUpdated"
  ): TypedContractEvent<
    TierPriceUpdatedEvent.InputTuple,
    TierPriceUpdatedEvent.OutputTuple,
    TierPriceUpdatedEvent.OutputObject
  >;

  filters: {
    "DurationUpdated(uint256)": TypedContractEvent<
      DurationUpdatedEvent.InputTuple,
      DurationUpdatedEvent.OutputTuple,
      DurationUpdatedEvent.OutputObject
    >;
    DurationUpdated: TypedContractEvent<
      DurationUpdatedEvent.InputTuple,
      DurationUpdatedEvent.OutputTuple,
      DurationUpdatedEvent.OutputObject
    >;

    "Subscribed(address,address,uint256,uint256)": TypedContractEvent<
      SubscribedEvent.InputTuple,
      SubscribedEvent.OutputTuple,
      SubscribedEvent.OutputObject
    >;
    Subscribed: TypedContractEvent<
      SubscribedEvent.InputTuple,
      SubscribedEvent.OutputTuple,
      SubscribedEvent.OutputObject
    >;

    "TierPriceUpdated(uint8,uint256)": TypedContractEvent<
      TierPriceUpdatedEvent.InputTuple,
      TierPriceUpdatedEvent.OutputTuple,
      TierPriceUpdatedEvent.OutputObject
    >;
    TierPriceUpdated: TypedContractEvent<
      TierPriceUpdatedEvent.InputTuple,
      TierPriceUpdatedEvent.OutputTuple,
      TierPriceUpdatedEvent.OutputObject
    >;
  };
}
