/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface AgentRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "agentList"
      | "agenticIdContract"
      | "agenticIdToAgent"
      | "agents"
      | "deregisterAgent"
      | "getAgentByAgenticId"
      | "getAgentCount"
      | "getAgenticId"
      | "getAgents"
      | "getNodeCount"
      | "getNodes"
      | "getVerifiedAgents"
      | "isVerifiedAgent"
      | "linkAgenticId"
      | "nodes"
      | "publishBatch"
      | "registerAgent"
      | "registerNode"
      | "registerVerifiedAgent"
      | "setAgenticIdContract"
      | "verifier"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AgentDeregistered"
      | "AgentRegistered"
      | "AgenticIdLinked"
      | "BatchPublished"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "agentList",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "agenticIdContract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "agenticIdToAgent",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "agents", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "deregisterAgent",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAgentByAgenticId",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAgentCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAgenticId",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAgents",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getNodeCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getNodes",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getVerifiedAgents",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isVerifiedAgent",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "linkAgenticId",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "nodes", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "publishBatch",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerAgent",
    values: [string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "registerNode",
    values: [string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "registerVerifiedAgent",
    values: [string, string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setAgenticIdContract",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "verifier", values?: undefined): string;

  decodeFunctionResult(functionFragment: "agentList", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "agenticIdContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "agenticIdToAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "agents", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "deregisterAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAgentByAgenticId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAgentCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAgenticId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getAgents", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getNodeCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getNodes", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getVerifiedAgents",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isVerifiedAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "linkAgenticId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "nodes", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "publishBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerNode",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerVerifiedAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAgenticIdContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "verifier", data: BytesLike): Result;
}

export namespace AgentDeregisteredEvent {
  export type InputTuple = [agentId: AddressLike];
  export type OutputTuple = [agentId: string];
  export interface OutputObject {
    agentId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgentRegisteredEvent {
  export type InputTuple = [
    agentId: AddressLike,
    name: string,
    tokenFocus: string,
    creator: AddressLike,
    agenticId: BigNumberish,
    isVerified: boolean
  ];
  export type OutputTuple = [
    agentId: string,
    name: string,
    tokenFocus: string,
    creator: string,
    agenticId: bigint,
    isVerified: boolean
  ];
  export interface OutputObject {
    agentId: string;
    name: string;
    tokenFocus: string;
    creator: string;
    agenticId: bigint;
    isVerified: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgenticIdLinkedEvent {
  export type InputTuple = [agentId: AddressLike, agenticId: BigNumberish];
  export type OutputTuple = [agentId: string, agenticId: bigint];
  export interface OutputObject {
    agentId: string;
    agenticId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BatchPublishedEvent {
  export type InputTuple = [rootHash: BytesLike, timestamp: BigNumberish];
  export type OutputTuple = [rootHash: string, timestamp: bigint];
  export interface OutputObject {
    rootHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AgentRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): AgentRegistry;
  waitForDeployment(): Promise<this>;

  interface: AgentRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  agentList: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  agenticIdContract: TypedContractMethod<[], [string], "view">;

  agenticIdToAgent: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  agents: TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, string, string, boolean, bigint, bigint, boolean] & {
        name: string;
        tokenFocus: string;
        description: string;
        creator: string;
        active: boolean;
        registeredAt: bigint;
        agenticId: bigint;
        isVerified: boolean;
      }
    ],
    "view"
  >;

  deregisterAgent: TypedContractMethod<[], [void], "nonpayable">;

  getAgentByAgenticId: TypedContractMethod<
    [agenticId: BigNumberish],
    [string],
    "view"
  >;

  getAgentCount: TypedContractMethod<[], [bigint], "view">;

  getAgenticId: TypedContractMethod<[agentId: AddressLike], [bigint], "view">;

  getAgents: TypedContractMethod<
    [offset: BigNumberish, limit: BigNumberish],
    [string[]],
    "view"
  >;

  getNodeCount: TypedContractMethod<[], [bigint], "view">;

  getNodes: TypedContractMethod<
    [offset: BigNumberish, limit: BigNumberish],
    [string[]],
    "view"
  >;

  getVerifiedAgents: TypedContractMethod<
    [offset: BigNumberish, limit: BigNumberish],
    [string[]],
    "view"
  >;

  isVerifiedAgent: TypedContractMethod<
    [agentId: AddressLike],
    [boolean],
    "view"
  >;

  linkAgenticId: TypedContractMethod<
    [agenticId: BigNumberish],
    [void],
    "nonpayable"
  >;

  nodes: TypedContractMethod<
    [agentId: AddressLike],
    [
      [string, string, string, string, boolean, bigint] & {
        name: string;
        tokenFocus: string;
        description: string;
        creator: string;
        active: boolean;
        registeredAt: bigint;
      }
    ],
    "view"
  >;

  publishBatch: TypedContractMethod<
    [rootHash: BytesLike],
    [void],
    "nonpayable"
  >;

  registerAgent: TypedContractMethod<
    [name: string, tokenFocus: string, description: string],
    [void],
    "nonpayable"
  >;

  registerNode: TypedContractMethod<
    [name: string, tokenFocus: string, description: string],
    [void],
    "nonpayable"
  >;

  registerVerifiedAgent: TypedContractMethod<
    [
      name: string,
      tokenFocus: string,
      description: string,
      agenticId: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  setAgenticIdContract: TypedContractMethod<
    [_agenticIdContract: AddressLike],
    [void],
    "nonpayable"
  >;

  verifier: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "agentList"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "agenticIdContract"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "agenticIdToAgent"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "agents"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, string, string, boolean, bigint, bigint, boolean] & {
        name: string;
        tokenFocus: string;
        description: string;
        creator: string;
        active: boolean;
        registeredAt: bigint;
        agenticId: bigint;
        isVerified: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "deregisterAgent"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getAgentByAgenticId"
  ): TypedContractMethod<[agenticId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getAgentCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getAgenticId"
  ): TypedContractMethod<[agentId: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getAgents"
  ): TypedContractMethod<
    [offset: BigNumberish, limit: BigNumberish],
    [string[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getNodeCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getNodes"
  ): TypedContractMethod<
    [offset: BigNumberish, limit: BigNumberish],
    [string[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getVerifiedAgents"
  ): TypedContractMethod<
    [offset: BigNumberish, limit: BigNumberish],
    [string[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "isVerifiedAgent"
  ): TypedContractMethod<[agentId: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "linkAgenticId"
  ): TypedContractMethod<[agenticId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "nodes"
  ): TypedContractMethod<
    [agentId: AddressLike],
    [
      [string, string, string, string, boolean, bigint] & {
        name: string;
        tokenFocus: string;
        description: string;
        creator: string;
        active: boolean;
        registeredAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "publishBatch"
  ): TypedContractMethod<[rootHash: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "registerAgent"
  ): TypedContractMethod<
    [name: string, tokenFocus: string, description: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registerNode"
  ): TypedContractMethod<
    [name: string, tokenFocus: string, description: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registerVerifiedAgent"
  ): TypedContractMethod<
    [
      name: string,
      tokenFocus: string,
      description: string,
      agenticId: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setAgenticIdContract"
  ): TypedContractMethod<
    [_agenticIdContract: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "verifier"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "AgentDeregistered"
  ): TypedContractEvent<
    AgentDeregisteredEvent.InputTuple,
    AgentDeregisteredEvent.OutputTuple,
    AgentDeregisteredEvent.OutputObject
  >;
  getEvent(
    key: "AgentRegistered"
  ): TypedContractEvent<
    AgentRegisteredEvent.InputTuple,
    AgentRegisteredEvent.OutputTuple,
    AgentRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "AgenticIdLinked"
  ): TypedContractEvent<
    AgenticIdLinkedEvent.InputTuple,
    AgenticIdLinkedEvent.OutputTuple,
    AgenticIdLinkedEvent.OutputObject
  >;
  getEvent(
    key: "BatchPublished"
  ): TypedContractEvent<
    BatchPublishedEvent.InputTuple,
    BatchPublishedEvent.OutputTuple,
    BatchPublishedEvent.OutputObject
  >;

  filters: {
    "AgentDeregistered(address)": TypedContractEvent<
      AgentDeregisteredEvent.InputTuple,
      AgentDeregisteredEvent.OutputTuple,
      AgentDeregisteredEvent.OutputObject
    >;
    AgentDeregistered: TypedContractEvent<
      AgentDeregisteredEvent.InputTuple,
      AgentDeregisteredEvent.OutputTuple,
      AgentDeregisteredEvent.OutputObject
    >;

    "AgentRegistered(address,string,string,address,uint256,bool)": TypedContractEvent<
      AgentRegisteredEvent.InputTuple,
      AgentRegisteredEvent.OutputTuple,
      AgentRegisteredEvent.OutputObject
    >;
    AgentRegistered: TypedContractEvent<
      AgentRegisteredEvent.InputTuple,
      AgentRegisteredEvent.OutputTuple,
      AgentRegisteredEvent.OutputObject
    >;

    "AgenticIdLinked(address,uint256)": TypedContractEvent<
      AgenticIdLinkedEvent.InputTuple,
      AgenticIdLinkedEvent.OutputTuple,
      AgenticIdLinkedEvent.OutputObject
    >;
    AgenticIdLinked: TypedContractEvent<
      AgenticIdLinkedEvent.InputTuple,
      AgenticIdLinkedEvent.OutputTuple,
      AgenticIdLinkedEvent.OutputObject
    >;

    "BatchPublished(bytes32,uint256)": TypedContractEvent<
      BatchPublishedEvent.InputTuple,
      BatchPublishedEvent.OutputTuple,
      BatchPublishedEvent.OutputObject
    >;
    BatchPublished: TypedContractEvent<
      BatchPublishedEvent.InputTuple,
      BatchPublishedEvent.OutputTuple,
      BatchPublishedEvent.OutputObject
    >;
  };
}
